### ISSUE TITLE
flash serial port autodetection

### ISSUE THREAD

**Issue by raboof** [badgeteam/ESP32-platform-firmware#103]
since 5462dc0e, the device to use for flashing is determined by:
```
CONFIG_ESPTOOLPY_PORT="`ls /dev/tty{USB0,.wchusbserial*,.SLAB_USBtoUART,ACMx} 2>/dev/null`"
```
This does not work for me (Debian): it seems the `{}` and the `*` wildcard don't seem to interact nicely, causing the expression not to return _any_ lines, not even /dev/ttyUSB0 .

/cc @tjclement

**Comment by tjclement** [comment]
That's interesting! This was done to support flashing many badges at once during the packing sweatshop, which was ran on Ubuntu (surprising, because it is a Debian derivative) and Fedora systems. Do you know of alternative ways on Debian?

**Comment by raboof** [comment]
wait, the backticks don't seem to be interpreted at all even... weird, investigating more

**Comment by raboof** [comment]
do you happen to know which `make` you were using on that machine? GNU Make 4.2.1 here.

**Comment by raboof** [comment]
It seems to not like the accolades notation here... what is your `dpkg -S /bin/sh`? also `dash`? `apt-cache policy dash` also `0.5.10.2-5`?

**Comment by renzenicolai** [comment]
Removed this autodetect thing. It doesn't work on Linux, defeating it's own main purpose of allowing easy use of the software on both mac and linux.

**Comment by tjclement** [comment]
I will look into this in the future. As my message above states, it does (did?) work on both standard Ubuntu desktop and Fedora, so it is incorrect to say it doesn't work on Linux.

It's a very handy feature for people new to embedded software development, since it abstracts away the different USB ICs used across all badges, so I see a lot of value to reimplement it later on.
