### ISSUE TITLE
Keeping in sync with upstream micropython

### ISSUE THREAD

**Issue by mkorkalo** [badgeteam/ESP32-platform-firmware#187]
I was looking for bluetooth support on the Disobey 2020 badge, and discovered there's some bluetooth support in the upstream micropython. But this project uses it's own fork and it's part of the repository (i.e. copy & paste the micropython repository to firmware/components/micropython).

I'm wondering why the micropython fork is a part of this repository. Doesn't that make it more difficult to keep in sync with upstream?
Would it make more sense to maintain it as a separate repository, and checkout the fork during build time.
Then, keeping in sync with upstream would be much easier: git rebase upstream/master or something.
As a side question, how much changes were made to the micropython fork? Would it be even possible to keep in sync with upstream?

**Comment by kliment** [comment]
Hey, thanks for looking into this! We use our own fork because we have it integrated into the espressif idf build system as a component. We also have many local changes to support our drivers and make sure the micropython functionality plays well with the idf and C components (upstream micropython assumes it's got the entire device to itself).

We used to have micropython as a separate repo but integrating the two build systems together was really painful and we had lots of problems with integration and changes to one side breaking the other. This firmware has lots of code implemented on the C side and micropython is only one component among many (although it's the main thing visible to the user). We are working on integration with upstream but the build system mismatch is a pain, and the way the micropython project is run makes it a bit difficult to get changes upstreamed. It is something we're looking into long-term but for the moment it's not really directly compatible on anything but an API-level.
